### ISSUE TITLE
uses examples?

### ISSUE THREAD

**Issue by Stavros3** [skroutz/elasticsearch-analysis-greeklish#13]
Hello. do you have a usage example or can you suggest something? i am new in ES ant try to use the plugin but i have stuck. i have installed successful but what next?
should i make a default settings for lowercase greeklish?
should the greek must put in the ES as lowercase? 
is it able to make a short example?

**Comment by qubusp** [comment]
OK, let me just summerize on the issue as I have been following Stavros on the FB group. 
1. When using your suggestion of documentation in ES 5.x, configuring indexes on node level doesn't work. It has to be done via POST.

```
PUT plastic
{
"settings":{
"analysis":{
"analyzer":{
"stem_analyzer":{
"type":"custom",
"tokenizer":"standard",
"filter": ["lower_greek", "stem_greek","greeklish_analysis"]
}
},
"filter": {
"lower_greek": {
"type":"lowercase",
"language":"greek"
},
"stem_greek": {
"type":"skroutz_stem_greek"
},
"greeklish_analysis":{
"type": "skroutz_greeklish",
"max_expansions": 15
}
}
}
},
"mappings": {
"as_export_data": {
"properties": {
"pr_name": {
"type": "text",
"analyzer": "stem_analyzer",
"fielddata": true
},
"pr_model": {
"type": "text",
"analyzer": "stem_analyzer",
"fielddata": true
},
"mnf_name": {
"type": "text",
"analyzer": "stem_analyzer",
"fielddata": true
},
"cat_names": {
"type": "text",
"analyzer": "stem_analyzer",
"fielddata": true
}
}
}
}
}
```
2. Please put the warning for the smallcase on top of the README.md in bold, as it confuses a lot of people. 
3. I guess the plugin is going to work for 6.x but please update, as more and more production systems are moving to that version. 



Thank you.

**Comment by lovemeblender** [comment]
Thank you for your suggestions and for getting in touch! 

Please note that we do accept pull requests - feel free to create one :)
