### ISSUE TITLE
Plugin Installation

### ISSUE THREAD

**Issue by cliapis** [skroutz/elasticsearch-analysis-greeklish#7]
Hi, I am trying o install your plugin and I get the following error:
`ERROR: Unknown plugin gr.skroutz/elasticsearch-analysis-greeklish/0.11`

The command o install plugins in the current elastic version is:
`elasticsearch-plugin install gr.skroutz/elasticsearch-analysis-greeklish/0.11`

I have also tried the following command which follows the current version's documentation with no luck.
`elasticsearch-plugin install elasticsearch-analysis-greeklish`

Please advise.
Thank you.

**Comment by greenonion** [comment]
Hello @cliapis, which Elasticsearch version are you using?

**Comment by cliapis** [comment]
Hi @greenonion I am using 5.2.1. I assume that the plugin is for 2.* version.

**Comment by greenonion** [comment]
Well it actually supports up to `1.5.x` series. We plan to release a version supporting the `5.x` (and probably the `2.x`) series in the near future (i.e. the next few months).

**Comment by cliapis** [comment]
Sounds great! Thanks a lot!
